/**
 * This file is a transformation of outputs generated by several Figma plugins.
 */
import { css } from 'styled-components';

import vars from'./utils/vars';

export const primitives = {
  '--colors-brand-primary-10': 'rgb(13, 22, 36)',
  '--colors-brand-primary-100': 'rgb(130, 178, 250)',
  '--colors-brand-primary-110': 'rgb(148, 191, 255)',
  '--colors-brand-primary-120': 'rgb(170, 204, 255)',
  '--colors-brand-primary-130': 'rgb(189, 215, 255)',
  '--colors-brand-primary-140': 'rgb(204, 224, 255)',
  '--colors-brand-primary-150': 'rgb(229, 239, 255)',
  '--colors-brand-primary-160': 'rgb(242, 247, 255)',
  '--colors-brand-primary-20': 'rgb(21, 37, 60)',
  '--colors-brand-primary-30': 'rgb(29, 49, 80)',
  '--colors-brand-primary-40': 'rgb(36, 61, 99)',
  '--colors-brand-primary-50': 'rgb(44, 75, 122)',
  '--colors-brand-primary-60': 'rgb(51, 88, 143)',
  '--colors-brand-primary-70': 'rgb(64, 110, 178)',
  '--colors-brand-primary-80': 'rgb(84, 134, 209)',
  '--colors-brand-primary-90': 'rgb(111, 161, 235)',
  '--colors-brand-secondary-10': 'rgb(41, 23, 10)',
  '--colors-brand-secondary-100': 'rgb(250, 158, 92)',
  '--colors-brand-secondary-110': 'rgb(250, 174, 120)',
  '--colors-brand-secondary-120': 'rgb(252, 189, 144)',
  '--colors-brand-secondary-130': 'rgb(255, 215, 186)',
  '--colors-brand-secondary-140': 'rgb(255, 225, 204)',
  '--colors-brand-secondary-150': 'rgb(255, 241, 232)',
  '--colors-brand-secondary-160': 'rgb(255, 252, 250)',
  '--colors-brand-secondary-20': 'rgb(61, 33, 13)',
  '--colors-brand-secondary-30': 'rgb(79, 43, 17)',
  '--colors-brand-secondary-40': 'rgb(99, 54, 22)',
  '--colors-brand-secondary-50': 'rgb(122, 65, 24)',
  '--colors-brand-secondary-60': 'rgb(145, 77, 28)',
  '--colors-brand-secondary-70': 'rgb(168, 88, 30)',
  '--colors-brand-secondary-80': 'rgb(194, 106, 43)',
  '--colors-brand-secondary-90': 'rgb(227, 129, 59)',
  '--colors-grey-10': 'rgb(21, 25, 31)',
  '--colors-grey-12': 'rgb(25, 29, 36)',
  '--colors-grey-14': 'rgb(30, 35, 43)',
  '--colors-grey-16': 'rgb(35, 41, 51)',
  '--colors-grey-18': 'rgb(41, 47, 59)',
  '--colors-grey-2': 'rgb(7, 8, 10)',
  '--colors-grey-20': 'rgb(44, 51, 64)',
  '--colors-grey-22': 'rgb(49, 57, 71)',
  '--colors-grey-24': 'rgb(55, 63, 79)',
  '--colors-grey-26': 'rgb(60, 70, 87)',
  '--colors-grey-28': 'rgb(65, 76, 94)',
  '--colors-grey-30': 'rgb(70, 82, 102)',
  '--colors-grey-32': 'rgb(77, 89, 110)',
  '--colors-grey-34': 'rgb(84, 97, 120)',
  '--colors-grey-36': 'rgb(91, 105, 128)',
  '--colors-grey-38': 'rgb(94, 108, 133)',
  '--colors-grey-4': 'rgb(11, 12, 15)',
  '--colors-grey-40': 'rgb(97, 111, 135)',
  '--colors-grey-42': 'rgb(101, 115, 140)',
  '--colors-grey-44': 'rgb(105, 120, 145)',
  '--colors-grey-46': 'rgb(108, 123, 150)',
  '--colors-grey-48': 'rgb(112, 128, 156)',
  '--colors-grey-50': 'rgb(116, 132, 161)',
  '--colors-grey-52': 'rgb(119, 136, 166)',
  '--colors-grey-54': 'rgb(123, 141, 171)',
  '--colors-grey-56': 'rgb(126, 144, 176)',
  '--colors-grey-58': 'rgb(130, 149, 181)',
  '--colors-grey-6': 'rgb(14, 16, 20)',
  '--colors-grey-60': 'rgb(134, 153, 186)',
  '--colors-grey-62': 'rgb(138, 157, 189)',
  '--colors-grey-64': 'rgb(143, 162, 194)',
  '--colors-grey-66': 'rgb(149, 167, 199)',
  '--colors-grey-68': 'rgb(155, 173, 204)',
  '--colors-grey-70': 'rgb(161, 179, 209)',
  '--colors-grey-72': 'rgb(167, 184, 214)',
  '--colors-grey-74': 'rgb(171, 189, 219)',
  '--colors-grey-76': 'rgb(180, 196, 224)',
  '--colors-grey-78': 'rgb(184, 201, 229)',
  '--colors-grey-8': 'rgb(18, 20, 26)',
  '--colors-grey-80': 'rgb(190, 205, 232)',
  '--colors-grey-82': 'rgb(197, 211, 235)',
  '--colors-grey-84': 'rgb(204, 216, 237)',
  '--colors-grey-86': 'rgb(213, 224, 242)',
  '--colors-grey-88': 'rgb(220, 229, 245)',
  '--colors-grey-90': 'rgb(227, 234, 247)',
  '--colors-grey-92': 'rgb(235, 240, 250)',
  '--colors-grey-94': 'rgb(240, 244, 250)',
  '--colors-grey-96': 'rgb(245, 248, 252)',
  '--colors-grey-98': 'rgb(249, 250, 252)',
  '--colors-grey-black': 'rgb(0, 0, 0)',
  '--colors-grey-white': 'rgb(255, 255, 255)',
  '--colors-grey-alpha-alpha-0': 'rgb(255, 255, 255, 0)',
  '--colors-grey-alpha-grey-14-alpha-0': 'rgb(30, 35, 43, 0)',
  '--colors-grey-alpha-grey-14-alpha-50': 'rgb(30, 35, 43, 0.5)',
  '--colors-grey-alpha-grey-14-alpha-80': 'rgb(30, 35, 43, 0.8)',
  '--colors-grey-alpha-grey-2-alpha-10': 'rgb(7, 8, 10, 0.1)',
  '--colors-grey-alpha-grey-2-alpha-15': 'rgb(7, 8, 10, 0.15)',
  '--colors-grey-alpha-grey-2-alpha-20': 'rgb(7, 8, 10, 0.2)',
  '--colors-grey-alpha-grey-2-alpha-25': 'rgb(7, 8, 10, 0.25)',
  '--colors-grey-alpha-grey-2-alpha-30': 'rgb(7, 8, 10, 0.3)',
  '--colors-grey-alpha-grey-2-alpha-40': 'rgb(7, 8, 10, 0.4)',
  '--colors-grey-alpha-grey-2-alpha-5': 'rgb(7, 8, 10, 0.05)',
  '--colors-grey-alpha-grey-2-alpha-50': 'rgb(7, 8, 10, 0.5)',
  '--colors-grey-alpha-grey-2-alpha-90': 'rgb(7, 8, 10, 0.9)',
  '--colors-grey-alpha-grey-30-alpha-0': 'rgb(70, 82, 102, 0)',
  '--colors-grey-alpha-grey-30-alpha-10': 'rgb(70, 82, 102, 0.1)',
  '--colors-grey-alpha-grey-30-alpha-15': 'rgb(70, 82, 102, 0.15)',
  '--colors-grey-alpha-grey-30-alpha-20': 'rgb(70, 82, 102, 0.2)',
  '--colors-grey-alpha-grey-30-alpha-25': 'rgb(70, 82, 102, 0.25)',
  '--colors-grey-alpha-grey-30-alpha-5': 'rgb(70, 82, 102, 0.05)',
  '--colors-grey-alpha-grey-50-alpha-0': 'rgb(116, 132, 161, 0)',
  '--colors-grey-alpha-grey-50-alpha-50': 'rgb(116, 132, 161, 0.5)',
  '--colors-grey-alpha-grey-88-alpha-25': 'rgb(220, 229, 245, 0.25)',
  '--colors-grey-alpha-grey-88-alpha-50': 'rgb(220, 229, 245, 0.5)',
  '--colors-grey-alpha-grey-88-alpha-90': 'rgb(220, 229, 245, 0.9)',
  '--colors-grey-alpha-white-alpha-0': 'rgb(255, 255, 255, 0)',
  '--colors-grey-alpha-white-alpha-10': 'rgb(255, 255, 255, 0.1)',
  '--colors-grey-alpha-white-alpha-30': 'rgb(255, 255, 255, 0.3)',
  '--colors-grey-alpha-white-alpha-50': 'rgb(255, 255, 255, 0.5)',
  '--colors-grey-alpha-white-alpha-80': 'rgb(255, 255, 255, 0.8)',
  '--colors-shared-dark-orange-default': 'rgb(230, 93, 25)',
  '--colors-shared-dark-orange-shade-10': 'rgb(173, 58, 0)',
  '--colors-shared-dark-orange-shade-40': 'rgb(71, 24, 0)',
  '--colors-shared-dark-orange-tint-30': 'rgb(237, 142, 94)',
  '--colors-shared-dark-orange-tint-40': 'rgb(245, 190, 163)',
  '--colors-shared-dark-orange-tint-60': 'rgb(252, 239, 232)',
  '--colors-shared-green-default': 'rgb(0, 153, 92)',
  '--colors-shared-green-shade-10': 'rgb(0, 128, 77)',
  '--colors-shared-green-shade-40': 'rgb(0, 38, 23)',
  '--colors-shared-green-tint-30': 'rgb(82, 204, 155)',
  '--colors-shared-green-tint-40': 'rgb(138, 229, 193)',
  '--colors-shared-green-tint-60': 'rgb(229, 255, 245)',
  '--colors-shared-red-default': 'rgb(229, 64, 87)',
  '--colors-shared-red-shade-10': 'rgb(204, 57, 77)',
  '--colors-shared-red-shade-20': 'rgb(182, 47, 65)',
  '--colors-shared-red-shade-40': 'rgb(63, 16, 22)',
  '--colors-shared-red-tint-30': 'rgb(236, 116, 132)',
  '--colors-shared-red-tint-40': 'rgb(245, 183, 191)',
  '--colors-shared-red-tint-60': 'rgb(253, 237, 239)',
  '--colors-shared-yellow-default': 'rgb(240, 183, 13)',
  '--colors-shared-yellow-shade-30': 'rgb(143, 107, 0)',
  '--colors-shared-yellow-shade-40': 'rgb(77, 57, 0)',
  '--colors-shared-yellow-tint-30': 'rgb(254, 216, 102)',
  '--colors-shared-yellow-tint-40': 'rgb(254, 235, 178)',
  '--colors-shared-yellow-tint-60': 'rgb(255, 250, 235)',
  '--number-values-0': '0px',
  '--number-values-1': '1px',
  '--number-values-2': '2px',
  '--number-values-3': '3px',
  '--number-values-4': '4px',
  '--number-values-5': '5px',
  '--number-values-6': '6px',
  '--number-values-8': '8px',
  '--number-values-10': '10px',
  '--number-values-12': '12px',
  '--number-values-14': '14px',
  '--number-values-16': '16px',
  '--number-values-20': '20px',
  '--number-values-24': '24px',
  '--number-values-28': '28px',
  '--number-values-32': '32px',
  '--number-values-48': '48px',
  '--number-values-64': '64px',
  '--number-values-circular': '10000px',
};

type ThemeName = string;
type ThemeToken = string;
type PrimitiveToken = keyof typeof primitives;

/**
 * While themes in the app are generally carried out using css variables, the tokens are in a form
 * of js objects to be equally easily accessible in js as in css, serving a single source of truth
 * for both worlds.
 *
 * The values of the theme objects are the keys of the "primitives" object.
 */
export const themes = {
  light: {
    '--color-brand-background-1-hover': '--colors-brand-primary-50',
    '--color-brand-background-1-pressed': '--colors-brand-primary-30',
    '--color-brand-background-1-rest': '--colors-brand-primary-70',
    '--color-brand-background-1-selected': '--colors-brand-primary-50',
    '--color-brand-background-2-hover': '--colors-brand-primary-130',
    '--color-brand-background-2-pressed': '--colors-brand-primary-110',
    '--color-brand-background-2-rest': '--colors-brand-primary-140',
    '--color-brand-background-3-hover': '--colors-brand-primary-140',
    '--color-brand-background-3-pressed': '--colors-brand-primary-100',
    '--color-brand-background-3-rest': '--colors-brand-primary-130',
    '--color-brand-background-3-selected': '--colors-brand-primary-140',
    '--color-brand-background-compound-hover': '--colors-brand-primary-90',
    '--color-brand-background-compound-pressed': '--colors-brand-primary-70',
    '--color-brand-background-compound-rest': '--colors-brand-primary-110',
    '--color-brand-background-glow-a': '--colors-brand-primary-130',
    '--color-brand-background-glow-b': '--colors-grey-alpha-alpha-0',
    '--color-brand-background-inverted-hover': '--colors-brand-primary-160',
    '--color-brand-background-inverted-pressed': '--colors-brand-primary-140',
    '--color-brand-background-inverted-rest': '--colors-grey-white',
    '--color-brand-background-inverted-selected': '--colors-brand-primary-150',
    '--color-brand-background-static-rest': '--colors-brand-primary-130',
    '--color-brand-foreground-1-rest': '--colors-brand-primary-70',
    '--color-brand-foreground-2-hover': '--colors-brand-primary-50',
    '--color-brand-foreground-2-pressed': '--colors-brand-primary-20',
    '--color-brand-foreground-2-rest': '--colors-brand-primary-60',
    '--color-brand-foreground-compound-hover': '--colors-brand-primary-90',
    '--color-brand-foreground-compound-pressed': '--colors-brand-primary-70',
    '--color-brand-foreground-compound-rest': '--colors-brand-primary-110',
    '--color-brand-foreground-inverted-hover': '--colors-brand-primary-110',
    '--color-brand-foreground-inverted-pressed': '--colors-brand-primary-100',
    '--color-brand-foreground-inverted-rest': '--colors-brand-primary-100',
    '--color-brand-foreground-link-hover': '--colors-brand-primary-50',
    '--color-brand-foreground-link-pressed': '--colors-brand-primary-30',
    '--color-brand-foreground-link-rest': '--colors-brand-primary-60',
    '--color-brand-foreground-link-selected': '--colors-brand-primary-60',
    '--color-brand-foreground-on-light-hover': '--colors-brand-primary-70',
    '--color-brand-foreground-on-light-pressed': '--colors-brand-primary-50',
    '--color-brand-foreground-on-light-rest': '--colors-brand-primary-80',
    '--color-brand-foreground-on-light-selected': '--colors-brand-primary-60',
    '--color-brand-stroke-1-rest': '--colors-brand-primary-100',
    '--color-brand-stroke-2-hover': '--colors-brand-primary-110',
    '--color-brand-stroke-2-pressed': '--colors-brand-primary-100',
    '--color-brand-stroke-2-rest': '--colors-brand-primary-120',
    '--color-brand-stroke-2-contrast-rest': '--colors-brand-primary-150',
    '--color-brand-stroke-compound-hover': '--colors-brand-primary-90',
    '--color-brand-stroke-compound-pressed': '--colors-brand-primary-70',
    '--color-brand-stroke-compound-rest': '--colors-brand-primary-110',
    '--color-neutral-background-1-hover': '--colors-grey-94',
    '--color-neutral-background-1-pressed': '--colors-grey-92',
    '--color-neutral-background-1-rest': '--colors-grey-98',
    '--color-neutral-background-1-selected': '--colors-grey-90',
    '--color-neutral-background-1a-hover': '--colors-grey-90',
    '--color-neutral-background-1a-pressed': '--colors-grey-84',
    '--color-neutral-background-1a-rest': '--colors-grey-92',
    '--color-neutral-background-1a-selected': '--colors-grey-88',
    '--color-neutral-background-2-hover': '--colors-grey-96',
    '--color-neutral-background-2-pressed': '--colors-grey-94',
    '--color-neutral-background-2-rest': '--colors-grey-white',
    '--color-neutral-background-2-selected': '--colors-grey-92',
    '--color-neutral-background-2a-hover': '--colors-grey-94',
    '--color-neutral-background-2a-pressed': '--colors-grey-84',
    '--color-neutral-background-2a-rest': '--colors-grey-96',
    '--color-neutral-background-2a-selected': '--colors-grey-88',
    '--color-neutral-background-3-hover': '--colors-grey-92',
    '--color-neutral-background-3-pressed': '--colors-grey-90',
    '--color-neutral-background-3-rest': '--colors-grey-96',
    '--color-neutral-background-3-selected': '--colors-grey-88',
    '--color-neutral-background-3a-hover': '--colors-grey-96',
    '--color-neutral-background-3a-pressed': '--colors-grey-88',
    '--color-neutral-background-3a-rest': '--colors-grey-white',
    '--color-neutral-background-3a-selected': '--colors-grey-92',
    '--color-neutral-background-4-hover': '--colors-grey-90',
    '--color-neutral-background-4-pressed': '--colors-grey-88',
    '--color-neutral-background-4-rest': '--colors-grey-94',
    '--color-neutral-background-4-selected': '--colors-grey-86',
    '--color-neutral-background-4a-hover': '--colors-grey-92',
    '--color-neutral-background-4a-pressed': '--colors-grey-86',
    '--color-neutral-background-4a-rest': '--colors-grey-98',
    '--color-neutral-background-4a-selected': '--colors-grey-90',
    '--color-neutral-background-5-hover': '--colors-grey-88',
    '--color-neutral-background-5-pressed': '--colors-grey-86',
    '--color-neutral-background-5-rest': '--colors-grey-92',
    '--color-neutral-background-5-selected': '--colors-grey-84',
    '--color-neutral-background-5a-hover': '--colors-grey-84',
    '--color-neutral-background-5a-pressed': '--colors-grey-76',
    '--color-neutral-background-5a-rest': '--colors-grey-88',
    '--color-neutral-background-5a-selected': '--colors-grey-80',
    '--color-neutral-background-6-rest': '--colors-grey-90',
    '--color-neutral-background-6a-rest': '--colors-grey-82',
    '--color-neutral-background-alpha-1-rest': '--colors-grey-alpha-grey-88-alpha-90',
    '--color-neutral-background-alpha-2-rest': '--colors-grey-alpha-grey-88-alpha-50',
    '--color-neutral-background-alpha-3-rest': '--colors-grey-alpha-grey-88-alpha-25',
    '--color-neutral-background-alpha-4-rest': '--colors-grey-alpha-white-alpha-30',
    '--color-neutral-background-canvas-rest': '--colors-grey-92',
    '--color-neutral-background-disabled-rest': '--colors-grey-88',
    '--color-neutral-background-gradient-color-a': '--colors-grey-90',
    '--color-neutral-background-gradient-color-b': '--colors-grey-96',
    '--color-neutral-background-inverted-rest': '--colors-grey-14',
    '--color-neutral-background-inverted-disabled-rest': '--colors-grey-alpha-white-alpha-10',
    '--color-neutral-background-overlay-rest': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-background-scrollbar-overlay-rest': '--colors-grey-alpha-grey-88-alpha-50',
    '--color-neutral-background-static-dark-rest': '--colors-grey-10',
    '--color-neutral-background-static-light-rest': '--colors-grey-white',
    '--color-neutral-background-stencil-1-rest': '--colors-grey-92',
    '--color-neutral-background-stencil-2-rest': '--colors-grey-96',
    '--color-neutral-background-stencil-3-rest': '--colors-grey-alpha-grey-88-alpha-50',
    '--color-neutral-background-subtle-hover': '--colors-grey-94',
    '--color-neutral-background-subtle-pressed': '--colors-grey-88',
    '--color-neutral-background-subtle-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-subtle-selected': '--colors-grey-90',
    '--color-neutral-background-subtle-inverted-hover': '--colors-grey-alpha-grey-2-alpha-10',
    '--color-neutral-background-subtle-inverted-pressed': '--colors-grey-alpha-grey-2-alpha-30',
    '--color-neutral-background-subtle-inverted-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-subtle-inverted-selected': '--colors-grey-alpha-grey-2-alpha-20',
    '--color-neutral-background-subtle-light-alpha-hover': '--colors-grey-alpha-white-alpha-80',
    '--color-neutral-background-subtle-light-alpha-pressed': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-background-subtle-light-alpha-selected': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-hover': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-pressed': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-selected': '--colors-grey-alpha-alpha-0',
    '--color-neutral-foreground-1-hover': '--colors-grey-14',
    '--color-neutral-foreground-1-pressed': '--colors-grey-14',
    '--color-neutral-foreground-1-rest': '--colors-grey-14',
    '--color-neutral-foreground-1-selected': '--colors-grey-14',
    '--color-neutral-foreground-2-hover': '--colors-grey-14',
    '--color-neutral-foreground-2-pressed': '--colors-grey-14',
    '--color-neutral-foreground-2-rest': '--colors-grey-26',
    '--color-neutral-foreground-2-selected': '--colors-grey-14',
    '--color-neutral-foreground-2-brand-hover': '--colors-brand-primary-90',
    '--color-neutral-foreground-2-brand-pressed': '--colors-brand-primary-80',
    '--color-neutral-foreground-2-brand-selected': '--colors-brand-primary-90',
    '--color-neutral-foreground-2-link-hover': '--colors-grey-14',
    '--color-neutral-foreground-2-link-pressed': '--colors-grey-14',
    '--color-neutral-foreground-2-link-rest': '--colors-grey-26',
    '--color-neutral-foreground-2-link-selected': '--colors-grey-14',
    '--color-neutral-foreground-3-hover': '--colors-grey-26',
    '--color-neutral-foreground-3-pressed': '--colors-grey-26',
    '--color-neutral-foreground-3-rest': '--colors-grey-38',
    '--color-neutral-foreground-3-selected': '--colors-grey-26',
    '--color-neutral-foreground-3-brand-hover': '--colors-brand-primary-80',
    '--color-neutral-foreground-3-brand-pressed': '--colors-brand-primary-70',
    '--color-neutral-foreground-3-brand-selected': '--colors-brand-primary-80',
    '--color-neutral-foreground-4-rest': '--colors-grey-46',
    '--color-neutral-foreground-disabled-rest': '--colors-grey-74',
    '--color-neutral-foreground-inverted-1-hover': '--colors-grey-white',
    '--color-neutral-foreground-inverted-1-pressed': '--colors-grey-white',
    '--color-neutral-foreground-inverted-1-rest': '--colors-grey-white',
    '--color-neutral-foreground-inverted-1-selected': '--colors-grey-white',
    '--color-neutral-foreground-inverted-2-rest': '--colors-grey-white',
    '--color-neutral-foreground-inverted-disabled-rest': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-foreground-inverted-link-hover': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-pressed': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-rest': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-selected': '--colors-grey-white',
    '--color-neutral-foreground-on-brand-rest': '--colors-grey-white',
    '--color-neutral-foreground-static-rest': '--colors-grey-14',
    '--color-neutral-foreground-static-inverted-rest': '--colors-grey-white',
    '--color-neutral-stroke-1-hover': '--colors-grey-78',
    '--color-neutral-stroke-1-pressed': '--colors-grey-70',
    '--color-neutral-stroke-1-rest': '--colors-grey-82',
    '--color-neutral-stroke-1-selected': '--colors-grey-74',
    '--color-neutral-stroke-2-rest': '--colors-grey-86',
    '--color-neutral-stroke-3-rest': '--colors-grey-white',
    '--color-neutral-stroke-accessible-hover': '--colors-grey-36',
    '--color-neutral-stroke-accessible-pressed': '--colors-grey-32',
    '--color-neutral-stroke-accessible-rest': '--colors-grey-40',
    '--color-neutral-stroke-accessible-selected': '--colors-brand-primary-130',
    '--color-neutral-stroke-alpha-rest': '--colors-grey-alpha-grey-2-alpha-5',
    '--color-neutral-stroke-disabled-rest': '--colors-grey-88',
    '--color-neutral-stroke-disabled-inverted-rest': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-stroke-focus-1-rest': '--colors-grey-white',
    '--color-neutral-stroke-focus-2-rest': '--colors-grey-black',
    '--color-neutral-stroke-gradient-color-a': '--colors-grey-white',
    '--color-neutral-stroke-gradient-color-b': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-on-brand-1-rest': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-hover': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-pressed': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-rest': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-selected': '--colors-grey-white',
    '--color-neutral-stroke-subtle-rest': '--colors-grey-94',
    '--color-neutral-stroke-transparent-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-transparent-disabled-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-transparent-interactive-rest': '--colors-grey-alpha-alpha-0',
    '--color-status-danger-background-1-rest': '--colors-shared-red-tint-60',
    '--color-status-danger-background-3-hover': '--colors-shared-red-shade-10',
    '--color-status-danger-background-3-pressed': '--colors-shared-red-shade-20',
    '--color-status-danger-background-3-rest': '--colors-shared-red-default',
    '--color-status-danger-background-3-selected': '--colors-shared-red-shade-40',
    '--color-status-danger-foreground-1-rest': '--colors-shared-red-shade-10',
    '--color-status-danger-foreground-3-rest': '--colors-shared-red-default',
    '--color-status-danger-stroke-1-rest': '--colors-shared-red-tint-40',
    '--color-status-danger-stroke-2-rest': '--colors-shared-red-default',
    '--color-status-danger-stroke-3-hover': '--colors-shared-red-shade-20',
    '--color-status-danger-stroke-3-pressed': '--colors-shared-red-tint-30',
    '--color-status-danger-stroke-3-rest': '--colors-shared-red-default',
    '--color-status-severe-background-1-rest': '--colors-shared-dark-orange-tint-60',
    '--color-status-severe-background-3-rest': '--colors-shared-dark-orange-default',
    '--color-status-severe-foreground-1-rest': '--colors-shared-dark-orange-shade-10',
    '--color-status-severe-foreground-3-rest': '--colors-shared-dark-orange-default',
    '--color-status-severe-stroke-1-rest': '--colors-shared-dark-orange-tint-40',
    '--color-status-severe-stroke-2-rest': '--colors-shared-dark-orange-default',
    '--color-status-success-background-1-rest': '--colors-shared-green-tint-60',
    '--color-status-success-background-3-rest': '--colors-shared-green-default',
    '--color-status-success-foreground-1-rest': '--colors-shared-green-shade-10',
    '--color-status-success-foreground-3-rest': '--colors-shared-green-default',
    '--color-status-success-stroke-1-rest': '--colors-shared-green-tint-40',
    '--color-status-success-stroke-2-rest': '--colors-shared-green-default',
    '--color-status-warning-background-1-rest': '--colors-shared-yellow-tint-60',
    '--color-status-warning-background-3-rest': '--colors-shared-yellow-default',
    '--color-status-warning-foreground-1-rest': '--colors-shared-yellow-shade-30',
    '--color-status-warning-foreground-2-rest': '--colors-shared-yellow-shade-30',
    '--color-status-warning-stroke-1-rest': '--colors-shared-yellow-tint-40',
    '--color-status-warning-stroke-2-rest': '--colors-shared-yellow-default',
    '--shadow-ambient': '--colors-grey-alpha-grey-30-alpha-15',
    '--shadow-ambient-brand': '--colors-brand-primary-80',
    '--shadow-ambient-darker': '--colors-grey-alpha-grey-30-alpha-20',
    '--shadow-ambient-lighter': '--colors-grey-alpha-grey-30-alpha-5',
    '--shadow-key': '--colors-grey-alpha-grey-30-alpha-15',
    '--shadow-key-brand': '--colors-brand-primary-80',
    '--shadow-key-darker': '--colors-grey-alpha-grey-30-alpha-25',
    '--shadow-key-lighter': '--colors-grey-alpha-grey-30-alpha-10',
    '--border-radius-none': '--number-values-0',
    '--border-radius-xxs-nudge': '--number-values-1',
    '--border-radius-xxs': '--number-values-2',
    '--border-radius-xs-nudge': '--number-values-3',
    '--border-radius-xs': '--number-values-4',
    '--border-radius-s-nudge': '--number-values-5',
    '--border-radius-s-nudge-2': '--number-values-6',
    '--border-radius-s': '--number-values-8',
    '--border-radius-m-nudge': '--number-values-10',
    '--border-radius-m': '--number-values-12',
    '--border-radius-l-nudge': '--number-values-14',
    '--border-radius-l': '--number-values-16',
    '--border-radius-xl': '--number-values-20',
    '--border-radius-xxl': '--number-values-24',
    '--border-radius-xxxl': '--number-values-32',
    '--border-radius-xxxxl': '--number-values-48',
    '--border-radius-circular': '--number-values-circular',
    '--shadow-02-ambient-spread': '--number-values-0',
    '--shadow-02-ambient-x': '--number-values-0',
    '--shadow-02-ambient-y': '--number-values-0',
    '--shadow-02-ambient-blur': '--number-values-2',
    '--shadow-02-key-spread': '--number-values-0',
    '--shadow-02-key-x': '--number-values-0',
    '--shadow-02-key-y': '--number-values-1',
    '--shadow-02-key-blur': '--number-values-2',
    '--shadow-04-ambient-spread': '--number-values-0',
    '--shadow-04-ambient-x': '--number-values-0',
    '--shadow-04-ambient-y': '--number-values-0',
    '--shadow-04-ambient-blur': '--number-values-2',
    '--shadow-04-key-spread': '--number-values-0',
    '--shadow-04-key-x': '--number-values-0',
    '--shadow-04-key-y': '--number-values-2',
    '--shadow-04-key-blur': '--number-values-4',
    '--shadow-08-ambient-spread': '--number-values-0',
    '--shadow-08-ambient-x': '--number-values-0',
    '--shadow-08-ambient-y': '--number-values-0',
    '--shadow-08-ambient-blur': '--number-values-2',
    '--shadow-08-key-spread': '--number-values-0',
    '--shadow-08-key-x': '--number-values-0',
    '--shadow-08-key-y': '--number-values-4',
    '--shadow-08-key-blur': '--number-values-8',
    '--shadow-16-ambient-spread': '--number-values-0',
    '--shadow-16-ambient-x': '--number-values-0',
    '--shadow-16-ambient-y': '--number-values-0',
    '--shadow-16-ambient-blur': '--number-values-2',
    '--shadow-16-key-spread': '--number-values-0',
    '--shadow-16-key-x': '--number-values-0',
    '--shadow-16-key-y': '--number-values-8',
    '--shadow-16-key-blur': '--number-values-16',
    '--shadow-28-ambient-spread': '--number-values-0',
    '--shadow-28-ambient-x': '--number-values-0',
    '--shadow-28-ambient-y': '--number-values-0',
    '--shadow-28-ambient-blur': '--number-values-8',
    '--shadow-28-key-spread': '--number-values-0',
    '--shadow-28-key-x': '--number-values-0',
    '--shadow-28-key-y': '--number-values-14',
    '--shadow-28-key-blur': '--number-values-28',
    '--shadow-64-ambient-spread': '--number-values-0',
    '--shadow-64-ambient-x': '--number-values-0',
    '--shadow-64-ambient-y': '--number-values-0',
    '--shadow-64-ambient-blur': '--number-values-8',
    '--shadow-64-key-spread': '--number-values-0',
    '--shadow-64-key-x': '--number-values-0',
    '--shadow-64-key-y': '--number-values-32',
    '--shadow-64-key-blur': '--number-values-64',
    '--spacing-none': '--number-values-0',
    '--spacing-xxs-nudge': '--number-values-1',
    '--spacing-xxs': '--number-values-2',
    '--spacing-xs-nudge': '--number-values-3',
    '--spacing-xs': '--number-values-4',
    '--spacing-s-nudge': '--number-values-5',
    '--spacing-s-nudge-2': '--number-values-6',
    '--spacing-s': '--number-values-8',
    '--spacing-m-nudge': '--number-values-10',
    '--spacing-m': '--number-values-12',
    '--spacing-l-nudge': '--number-values-14',
    '--spacing-l': '--number-values-16',
    '--spacing-xl': '--number-values-20',
    '--spacing-xxl': '--number-values-24',
    '--spacing-xxxl': '--number-values-32',
    '--spacing-xxxxl': '--number-values-48',
  },
  dark: {
    '--color-brand-background-1-hover': '--colors-brand-primary-100',
    '--color-brand-background-1-pressed': '--colors-brand-primary-90',
    '--color-brand-background-1-rest': '--colors-brand-primary-120',
    '--color-brand-background-1-selected': '--colors-brand-primary-80',
    '--color-brand-background-2-hover': '--colors-brand-primary-40',
    '--color-brand-background-2-pressed': '--colors-brand-primary-10',
    '--color-brand-background-2-rest': '--colors-brand-primary-20',
    '--color-brand-background-3-hover': '--colors-brand-primary-50',
    '--color-brand-background-3-pressed': '--colors-brand-primary-20',
    '--color-brand-background-3-rest': '--colors-brand-primary-30',
    '--color-brand-background-3-selected': '--colors-brand-primary-50',
    '--color-brand-background-compound-hover': '--colors-brand-primary-100',
    '--color-brand-background-compound-pressed': '--colors-brand-primary-80',
    '--color-brand-background-compound-rest': '--colors-brand-primary-120',
    '--color-brand-background-glow-a': '--colors-brand-primary-40',
    '--color-brand-background-glow-b': '--colors-grey-alpha-grey-14-alpha-0',
    '--color-brand-background-inverted-hover': '--colors-brand-primary-160',
    '--color-brand-background-inverted-pressed': '--colors-brand-primary-140',
    '--color-brand-background-inverted-rest': '--colors-grey-white',
    '--color-brand-background-inverted-selected': '--colors-brand-primary-150',
    '--color-brand-background-static-rest': '--colors-brand-primary-130',
    '--color-brand-foreground-1-rest': '--colors-brand-primary-140',
    '--color-brand-foreground-2-hover': '--colors-brand-primary-140',
    '--color-brand-foreground-2-pressed': '--colors-brand-primary-160',
    '--color-brand-foreground-2-rest': '--colors-brand-primary-120',
    '--color-brand-foreground-compound-hover': '--colors-brand-primary-100',
    '--color-brand-foreground-compound-pressed': '--colors-brand-primary-80',
    '--color-brand-foreground-compound-rest': '--colors-brand-primary-120',
    '--color-brand-foreground-inverted-hover': '--colors-brand-primary-70',
    '--color-brand-foreground-inverted-pressed': '--colors-brand-primary-60',
    '--color-brand-foreground-inverted-rest': '--colors-brand-primary-80',
    '--color-brand-foreground-link-hover': '--colors-brand-primary-110',
    '--color-brand-foreground-link-pressed': '--colors-brand-primary-90',
    '--color-brand-foreground-link-rest': '--colors-brand-primary-100',
    '--color-brand-foreground-link-selected': '--colors-brand-primary-100',
    '--color-brand-foreground-on-light-hover': '--colors-brand-primary-70',
    '--color-brand-foreground-on-light-pressed': '--colors-brand-primary-50',
    '--color-brand-foreground-on-light-rest': '--colors-brand-primary-80',
    '--color-brand-foreground-on-light-selected': '--colors-brand-primary-60',
    '--color-brand-stroke-1-rest': '--colors-brand-primary-140',
    '--color-brand-stroke-2-hover': '--colors-brand-primary-150',
    '--color-brand-stroke-2-pressed': '--colors-brand-primary-130',
    '--color-brand-stroke-2-rest': '--colors-brand-primary-140',
    '--color-brand-stroke-2-contrast-rest': '--colors-brand-primary-30',
    '--color-brand-stroke-compound-hover': '--colors-brand-primary-100',
    '--color-brand-stroke-compound-pressed': '--colors-brand-primary-80',
    '--color-brand-stroke-compound-rest': '--colors-brand-primary-120',
    '--color-neutral-background-1-hover': '--colors-grey-20',
    '--color-neutral-background-1-pressed': '--colors-grey-18',
    '--color-neutral-background-1-rest': '--colors-grey-14',
    '--color-neutral-background-1-selected': '--colors-grey-16',
    '--color-neutral-background-1a-hover': '--colors-grey-8',
    '--color-neutral-background-1a-pressed': '--colors-grey-14',
    '--color-neutral-background-1a-rest': '--colors-grey-4',
    '--color-neutral-background-1a-selected': '--colors-grey-10',
    '--color-neutral-background-2-hover': '--colors-grey-16',
    '--color-neutral-background-2-pressed': '--colors-grey-14',
    '--color-neutral-background-2-rest': '--colors-grey-10',
    '--color-neutral-background-2-selected': '--colors-grey-12',
    '--color-neutral-background-2a-hover': '--colors-grey-18',
    '--color-neutral-background-2a-pressed': '--colors-grey-24',
    '--color-neutral-background-2a-rest': '--colors-grey-6',
    '--color-neutral-background-2a-selected': '--colors-grey-20',
    '--color-neutral-background-3-hover': '--colors-grey-14',
    '--color-neutral-background-3-pressed': '--colors-grey-12',
    '--color-neutral-background-3-rest': '--colors-grey-8',
    '--color-neutral-background-3-selected': '--colors-grey-10',
    '--color-neutral-background-3a-hover': '--colors-grey-20',
    '--color-neutral-background-3a-pressed': '--colors-grey-28',
    '--color-neutral-background-3a-rest': '--colors-grey-10',
    '--color-neutral-background-3a-selected': '--colors-grey-24',
    '--color-neutral-background-4-hover': '--colors-grey-12',
    '--color-neutral-background-4-pressed': '--colors-grey-10',
    '--color-neutral-background-4-rest': '--colors-grey-6',
    '--color-neutral-background-4-selected': '--colors-grey-8',
    '--color-neutral-background-4a-hover': '--colors-grey-24',
    '--color-neutral-background-4a-pressed': '--colors-grey-32',
    '--color-neutral-background-4a-rest': '--colors-grey-14',
    '--color-neutral-background-4a-selected': '--colors-grey-28',
    '--color-neutral-background-5-hover': '--colors-grey-14',
    '--color-neutral-background-5-pressed': '--colors-grey-12',
    '--color-neutral-background-5-rest': '--colors-grey-8',
    '--color-neutral-background-5-selected': '--colors-grey-10',
    '--color-neutral-background-5a-hover': '--colors-grey-28',
    '--color-neutral-background-5a-pressed': '--colors-grey-34',
    '--color-neutral-background-5a-rest': '--colors-grey-16',
    '--color-neutral-background-5a-selected': '--colors-grey-30',
    '--color-neutral-background-6-rest': '--colors-grey-20',
    '--color-neutral-background-6a-rest': '--colors-grey-36',
    '--color-neutral-background-alpha-1-rest': '--colors-grey-alpha-grey-2-alpha-90',
    '--color-neutral-background-alpha-2-rest': '--colors-grey-alpha-grey-2-alpha-50',
    '--color-neutral-background-alpha-3-rest': '--colors-grey-alpha-grey-2-alpha-25',
    '--color-neutral-background-alpha-4-rest': '--colors-grey-alpha-grey-30-alpha-5',
    '--color-neutral-background-canvas-rest': '--colors-grey-4',
    '--color-neutral-background-disabled-rest': '--colors-grey-12',
    '--color-neutral-background-gradient-color-a': '--colors-grey-2',
    '--color-neutral-background-gradient-color-b': '--colors-grey-6',
    '--color-neutral-background-inverted-rest': '--colors-grey-white',
    '--color-neutral-background-inverted-disabled-rest': '--colors-grey-alpha-white-alpha-10',
    '--color-neutral-background-overlay-rest': '--colors-grey-alpha-grey-2-alpha-50',
    '--color-neutral-background-scrollbar-overlay-rest': '--colors-grey-alpha-grey-50-alpha-50',
    '--color-neutral-background-static-dark-rest': '--colors-grey-10',
    '--color-neutral-background-static-light-rest': '--colors-grey-white',
    '--color-neutral-background-stencil-1-rest': '--colors-grey-18',
    '--color-neutral-background-stencil-2-rest': '--colors-grey-14',
    '--color-neutral-background-stencil-3-rest': '--colors-grey-alpha-grey-30-alpha-10',
    '--color-neutral-background-subtle-hover': '--colors-grey-16',
    '--color-neutral-background-subtle-pressed': '--colors-grey-14',
    '--color-neutral-background-subtle-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-subtle-selected': '--colors-grey-12',
    '--color-neutral-background-subtle-inverted-hover': '--colors-grey-alpha-grey-2-alpha-10',
    '--color-neutral-background-subtle-inverted-pressed': '--colors-grey-alpha-grey-2-alpha-30',
    '--color-neutral-background-subtle-inverted-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-subtle-inverted-selected': '--colors-grey-alpha-grey-2-alpha-20',
    '--color-neutral-background-subtle-light-alpha-hover': '--colors-grey-alpha-grey-14-alpha-80',
    '--color-neutral-background-subtle-light-alpha-pressed': '--colors-grey-alpha-grey-14-alpha-50',
    '--color-neutral-background-subtle-light-alpha-selected': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-hover': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-pressed': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-background-transparent-selected': '--colors-grey-alpha-alpha-0',
    '--color-neutral-foreground-1-hover': '--colors-grey-white',
    '--color-neutral-foreground-1-pressed': '--colors-grey-white',
    '--color-neutral-foreground-1-rest': '--colors-grey-white',
    '--color-neutral-foreground-1-selected': '--colors-grey-white',
    '--color-neutral-foreground-2-hover': '--colors-grey-white',
    '--color-neutral-foreground-2-pressed': '--colors-grey-white',
    '--color-neutral-foreground-2-rest': '--colors-grey-84',
    '--color-neutral-foreground-2-selected': '--colors-grey-white',
    '--color-neutral-foreground-2-brand-hover': '--colors-brand-primary-140',
    '--color-neutral-foreground-2-brand-pressed': '--colors-brand-primary-130',
    '--color-neutral-foreground-2-brand-selected': '--colors-brand-primary-140',
    '--color-neutral-foreground-2-link-hover': '--colors-grey-white',
    '--color-neutral-foreground-2-link-pressed': '--colors-grey-white',
    '--color-neutral-foreground-2-link-rest': '--colors-grey-84',
    '--color-neutral-foreground-2-link-selected': '--colors-grey-white',
    '--color-neutral-foreground-3-hover': '--colors-grey-84',
    '--color-neutral-foreground-3-pressed': '--colors-grey-84',
    '--color-neutral-foreground-3-rest': '--colors-grey-68',
    '--color-neutral-foreground-3-selected': '--colors-grey-84',
    '--color-neutral-foreground-3-brand-hover': '--colors-brand-primary-100',
    '--color-neutral-foreground-3-brand-pressed': '--colors-brand-primary-90',
    '--color-neutral-foreground-3-brand-selected': '--colors-brand-primary-100',
    '--color-neutral-foreground-4-rest': '--colors-grey-54',
    '--color-neutral-foreground-disabled-rest': '--colors-grey-36',
    '--color-neutral-foreground-inverted-1-hover': '--colors-grey-14',
    '--color-neutral-foreground-inverted-1-pressed': '--colors-grey-14',
    '--color-neutral-foreground-inverted-1-rest': '--colors-grey-14',
    '--color-neutral-foreground-inverted-1-selected': '--colors-grey-14',
    '--color-neutral-foreground-inverted-2-rest': '--colors-grey-20',
    '--color-neutral-foreground-inverted-disabled-rest': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-foreground-inverted-link-hover': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-pressed': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-rest': '--colors-grey-white',
    '--color-neutral-foreground-inverted-link-selected': '--colors-grey-white',
    '--color-neutral-foreground-on-brand-rest': '--colors-grey-2',
    '--color-neutral-foreground-static-rest': '--colors-grey-14',
    '--color-neutral-foreground-static-inverted-rest': '--colors-grey-white',
    '--color-neutral-stroke-1-hover': '--colors-grey-46',
    '--color-neutral-stroke-1-pressed': '--colors-grey-42',
    '--color-neutral-stroke-1-rest': '--colors-grey-40',
    '--color-neutral-stroke-1-selected': '--colors-grey-44',
    '--color-neutral-stroke-2-rest': '--colors-grey-20',
    '--color-neutral-stroke-3-rest': '--colors-grey-10',
    '--color-neutral-stroke-accessible-hover': '--colors-grey-74',
    '--color-neutral-stroke-accessible-pressed': '--colors-grey-70',
    '--color-neutral-stroke-accessible-rest': '--colors-grey-68',
    '--color-neutral-stroke-accessible-selected': '--colors-brand-primary-140',
    '--color-neutral-stroke-alpha-rest': '--colors-grey-alpha-white-alpha-10',
    '--color-neutral-stroke-disabled-rest': '--colors-grey-26',
    '--color-neutral-stroke-disabled-inverted-rest': '--colors-grey-alpha-white-alpha-50',
    '--color-neutral-stroke-focus-1-rest': '--colors-grey-black',
    '--color-neutral-stroke-focus-2-rest': '--colors-grey-white',
    '--color-neutral-stroke-gradient-color-a': '--colors-grey-16',
    '--color-neutral-stroke-gradient-color-b': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-on-brand-1-rest': '--colors-grey-16',
    '--color-neutral-stroke-on-brand-2-hover': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-pressed': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-rest': '--colors-grey-white',
    '--color-neutral-stroke-on-brand-2-selected': '--colors-grey-white',
    '--color-neutral-stroke-subtle-rest': '--colors-grey-16',
    '--color-neutral-stroke-transparent-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-transparent-disabled-rest': '--colors-grey-alpha-alpha-0',
    '--color-neutral-stroke-transparent-interactive-rest': '--colors-grey-alpha-alpha-0',
    '--color-status-danger-background-1-rest': '--colors-shared-red-shade-40',
    '--color-status-danger-background-3-hover': '--colors-shared-red-shade-10',
    '--color-status-danger-background-3-pressed': '--colors-shared-red-shade-20',
    '--color-status-danger-background-3-rest': '--colors-shared-red-default',
    '--color-status-danger-background-3-selected': '--colors-shared-red-shade-40',
    '--color-status-danger-foreground-1-rest': '--colors-shared-red-tint-30',
    '--color-status-danger-foreground-3-rest': '--colors-shared-red-tint-40',
    '--color-status-danger-stroke-1-rest': '--colors-shared-red-default',
    '--color-status-danger-stroke-2-rest': '--colors-shared-red-tint-30',
    '--color-status-danger-stroke-3-hover': '--colors-shared-red-shade-20',
    '--color-status-danger-stroke-3-pressed': '--colors-shared-red-tint-30',
    '--color-status-danger-stroke-3-rest': '--colors-shared-red-default',
    '--color-status-severe-background-1-rest': '--colors-shared-dark-orange-shade-40',
    '--color-status-severe-background-3-rest': '--colors-shared-dark-orange-default',
    '--color-status-severe-foreground-1-rest': '--colors-shared-dark-orange-tint-30',
    '--color-status-severe-foreground-3-rest': '--colors-shared-dark-orange-tint-30',
    '--color-status-severe-stroke-1-rest': '--colors-shared-dark-orange-default',
    '--color-status-severe-stroke-2-rest': '--colors-shared-dark-orange-tint-40',
    '--color-status-success-background-1-rest': '--colors-shared-green-shade-40',
    '--color-status-success-background-3-rest': '--colors-shared-green-default',
    '--color-status-success-foreground-1-rest': '--colors-shared-green-tint-30',
    '--color-status-success-foreground-3-rest': '--colors-shared-green-tint-40',
    '--color-status-success-stroke-1-rest': '--colors-shared-green-default',
    '--color-status-success-stroke-2-rest': '--colors-shared-green-tint-40',
    '--color-status-warning-background-1-rest': '--colors-shared-yellow-shade-40',
    '--color-status-warning-background-3-rest': '--colors-shared-yellow-default',
    '--color-status-warning-foreground-1-rest': '--colors-shared-yellow-tint-30',
    '--color-status-warning-foreground-2-rest': '--colors-shared-yellow-tint-40',
    '--color-status-warning-stroke-1-rest': '--colors-shared-yellow-default',
    '--color-status-warning-stroke-2-rest': '--colors-shared-yellow-tint-40',
    '--shadow-ambient': '--colors-grey-alpha-grey-2-alpha-30',
    '--shadow-ambient-brand': '--colors-brand-primary-80',
    '--shadow-ambient-darker': '--colors-grey-alpha-grey-2-alpha-40',
    '--shadow-ambient-lighter': '--colors-grey-alpha-grey-2-alpha-15',
    '--shadow-key': '--colors-grey-alpha-grey-2-alpha-30',
    '--shadow-key-brand': '--colors-brand-primary-80',
    '--shadow-key-darker': '--colors-grey-alpha-grey-2-alpha-50',
    '--shadow-key-lighter': '--colors-grey-alpha-grey-2-alpha-15',
    '--border-radius-none': '--number-values-0',
    '--border-radius-xxs-nudge': '--number-values-1',
    '--border-radius-xxs': '--number-values-2',
    '--border-radius-xs-nudge': '--number-values-3',
    '--border-radius-xs': '--number-values-4',
    '--border-radius-s-nudge': '--number-values-5',
    '--border-radius-s-nudge-2': '--number-values-6',
    '--border-radius-s': '--number-values-8',
    '--border-radius-m-nudge': '--number-values-10',
    '--border-radius-m': '--number-values-12',
    '--border-radius-l-nudge': '--number-values-14',
    '--border-radius-l': '--number-values-16',
    '--border-radius-xl': '--number-values-20',
    '--border-radius-xxl': '--number-values-24',
    '--border-radius-xxxl': '--number-values-32',
    '--border-radius-xxxxl': '--number-values-48',
    '--border-radius-circular': '--number-values-circular',
    '--shadow-02-ambient-spread': '--number-values-0',
    '--shadow-02-ambient-x': '--number-values-0',
    '--shadow-02-ambient-y': '--number-values-0',
    '--shadow-02-ambient-blur': '--number-values-2',
    '--shadow-02-key-spread': '--number-values-0',
    '--shadow-02-key-x': '--number-values-0',
    '--shadow-02-key-y': '--number-values-1',
    '--shadow-02-key-blur': '--number-values-2',
    '--shadow-04-ambient-spread': '--number-values-0',
    '--shadow-04-ambient-x': '--number-values-0',
    '--shadow-04-ambient-y': '--number-values-0',
    '--shadow-04-ambient-blur': '--number-values-2',
    '--shadow-04-key-spread': '--number-values-0',
    '--shadow-04-key-x': '--number-values-0',
    '--shadow-04-key-y': '--number-values-2',
    '--shadow-04-key-blur': '--number-values-4',
    '--shadow-08-ambient-spread': '--number-values-0',
    '--shadow-08-ambient-x': '--number-values-0',
    '--shadow-08-ambient-y': '--number-values-0',
    '--shadow-08-ambient-blur': '--number-values-2',
    '--shadow-08-key-spread': '--number-values-0',
    '--shadow-08-key-x': '--number-values-0',
    '--shadow-08-key-y': '--number-values-4',
    '--shadow-08-key-blur': '--number-values-8',
    '--shadow-16-ambient-spread': '--number-values-0',
    '--shadow-16-ambient-x': '--number-values-0',
    '--shadow-16-ambient-y': '--number-values-0',
    '--shadow-16-ambient-blur': '--number-values-2',
    '--shadow-16-key-spread': '--number-values-0',
    '--shadow-16-key-x': '--number-values-0',
    '--shadow-16-key-y': '--number-values-8',
    '--shadow-16-key-blur': '--number-values-16',
    '--shadow-28-ambient-spread': '--number-values-0',
    '--shadow-28-ambient-x': '--number-values-0',
    '--shadow-28-ambient-y': '--number-values-0',
    '--shadow-28-ambient-blur': '--number-values-8',
    '--shadow-28-key-spread': '--number-values-0',
    '--shadow-28-key-x': '--number-values-0',
    '--shadow-28-key-y': '--number-values-14',
    '--shadow-28-key-blur': '--number-values-28',
    '--shadow-64-ambient-spread': '--number-values-0',
    '--shadow-64-ambient-x': '--number-values-0',
    '--shadow-64-ambient-y': '--number-values-0',
    '--shadow-64-ambient-blur': '--number-values-8',
    '--shadow-64-key-spread': '--number-values-0',
    '--shadow-64-key-x': '--number-values-0',
    '--shadow-64-key-y': '--number-values-32',
    '--shadow-64-key-blur': '--number-values-64',
    '--spacing-none': '--number-values-0',
    '--spacing-xxs-nudge': '--number-values-1',
    '--spacing-xxs': '--number-values-2',
    '--spacing-xs-nudge': '--number-values-3',
    '--spacing-xs': '--number-values-4',
    '--spacing-s-nudge': '--number-values-5',
    '--spacing-s-nudge-2': '--number-values-6',
    '--spacing-s': '--number-values-8',
    '--spacing-m-nudge': '--number-values-10',
    '--spacing-m': '--number-values-12',
    '--spacing-l-nudge': '--number-values-14',
    '--spacing-l': '--number-values-16',
    '--spacing-xl': '--number-values-20',
    '--spacing-xxl': '--number-values-24',
    '--spacing-xxxl': '--number-values-32',
    '--spacing-xxxxl': '--number-values-48',
  },
} as const satisfies Record<ThemeName, Record<ThemeToken, PrimitiveToken>>;

export const typography = {
  web: {
    caption2: css`
      font-size: 11px;
      font-family: Inter, sans-serif;
      line-height: 16px; /* 145.455% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    caption2Strong: css`
      font-size: 11px;
      font-family: Inter, sans-serif; 
      line-height: 16px; /* 145.455% */ 
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    caption1: css`
      font-size: 13px;
      font-family: Inter, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    caption1Strong: css`
      font-size: 13px;
      font-family: Inter, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    caption1Stronger: css`
      font-size: 13px;
      font-family: Inter, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 700;
      font-style: normal;
      letter-spacing: 0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    body1: css`
      font-size: 14px;
      font-family: Inter, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    body1Strong: css`
      font-size: 14px;
      font-family: Inter, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    body1Stronger: css`
      font-size: 14px;
      font-family: Inter, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 700;
      font-style: normal;
      letter-spacing: 0;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    body2: css`
      font-size: 16px;
      font-family: Inter, sans-serif;
      line-height: 24px; /* 150% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: -0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,

    subtitle2: css`
      font-size: 16px;
      font-family: Inter, sans-serif;
      line-height: 24px; /* 150% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: -0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    subtitle2Stronger: css`
      font-size: 16px;
      font-family: Inter, sans-serif;
      line-height: 24px; /* 150% */
      font-weight: 700;
      font-style: normal;
      letter-spacing: -0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    subtitle1: css`
      font-size: 20px;
      font-family: Inter, sans-serif;
      line-height: 25px; /* 125% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: -0.25px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    title3: css`
      font-size: 24px;
      font-family: Inter, sans-serif;
      line-height: 30px; /* 125% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: -0.15px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    title2: css`
      font-size: 28px;
      font-family: Inter, sans-serif;
      line-height: 34px; /* 121.429% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.4px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    title1: css`
      font-size: 32px;
      font-family: Inter, sans-serif;
      line-height: 38px; /* 118.75% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.4px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    largeTitle: css`
      font-size: 40px;
      font-family: Inter, sans-serif;
      line-height: 48px; /* 120% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.4px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
    display: css`
      font-size: 68px;
      font-family: Inter, sans-serif;
      line-height: 82px; /* 120.588% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.25px;

      font-variant-numeric: lining-nums tabular-nums;
      font-feature-settings: 'cv01' on;
    `,
  },
  decorative: {
    caption2: css`
      font-size: 11px;
      font-family: Borna, sans-serif;
      line-height: 14px; /* 127.273% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    caption2Strong: css`
      font-size: 11px;
      font-family: Borna, sans-serif;
      line-height: 16px; /* 145.455% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    caption1: css`
      font-size: 13px;
      font-family: Borna, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    caption1Strong: css`
      font-size: 13px;
      font-family: Borna, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    caption1Stronger: css`
      font-size: 13px;
      font-family: Borna, sans-serif;
      line-height: 18px; /* 138.462% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    body1: css`
      font-size: 14px;
      font-family: Borna, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    body1Strong: css`
      font-size: 14px;
      font-family: Borna, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    body1Stronger: css`
      font-size: 14px;
      font-family: Borna, sans-serif;
      line-height: 20px; /* 142.857% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    body2: css`
      font-size: 16px;
      font-family: Borna, sans-serif;
      line-height: 22px; /* 137.5% */
      font-weight: 400;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    body2Strong: css`
      font-size: 16px;
      font-family: Borna, sans-serif;
      line-height: 22px; /* 137.5% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;
    `,
    subtitle2: css`
      font-size: 16px;
      font-family: Borna, sans-serif;
      line-height: 20px; /* 125% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.25px;

      font-feature-settings: 'ss01' on;
    `,
    subtitle2Stronger: css`
      font-size: 16px;
      font-family: Borna, sans-serif;
      line-height: 20px; /* 125% */
      font-weight: 600;
      font-style: normal;
      letter-spacing: 0.25px;

      font-feature-settings: 'ss01' on;
    `,
    subtitle1: css`
      font-size: 20px;
      font-family: Borna, sans-serif;
      line-height: 24px; /* 120% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0.15px;

      font-feature-settings: 'ss01' on;
    `,
    title3: css`
      font-size: 24px;
      font-family: Borna, sans-serif;
      line-height: 30px; /* 125% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-feature-settings: 'ss01' on;
    `,
    title2: css`
      font-size: 28px;
      font-family: Borna, sans-serif;
      line-height: 34px; /* 121.429% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-feature-settings: 'ss01' on;
    `,
    title1: css`
      font-size: 32px;
      font-family: Borna, sans-serif;
      line-height: 38px; /* 118.75% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-feature-settings: 'ss01' on;
    `,
    largeTitle: css`
      font-size: 40px;
      font-family: Borna, sans-serif;
      line-height: 44px; /* 110% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-feature-settings: 'ss01' on;
    `,
    display: css`
      font-size: 68px;
      font-family: Borna, sans-serif;
      line-height: 80px; /* 117.647% */
      font-weight: 500;
      font-style: normal;
      letter-spacing: 0;

      font-feature-settings: 'ss01' on;
    `,
  },
};

export const backgroundFilters = {
  backgroundBlur1: css`
    backdrop-filter: blur(1px);
  `,
  backgroundBlur6: css`
    backdrop-filter: blur(3px);
  `,
  backgroundBlur8: css`
    backdrop-filter: blur(8px);
  `,
};

export const boxShadows = {
  shadow02: css`
    box-shadow:
      ${vars('--shadow-02-ambient-x')} ${vars('--shadow-02-ambient-y')} ${vars('--shadow-02-ambient-blur')} ${vars('--shadow-02-ambient-spread')} ${vars('--shadow-ambient')},
      ${vars('--shadow-02-key-x')} ${vars('--shadow-02-key-y')} ${vars('--shadow-02-key-blur')} ${vars('--shadow-02-key-spread')} ${vars('--shadow-key')};
  `,
  shadow04: css`
    box-shadow:
      ${vars('--shadow-04-ambient-x')} ${vars('--shadow-04-ambient-y')} ${vars('--shadow-04-ambient-blur')} ${vars('--shadow-04-ambient-spread')} ${vars('--shadow-ambient')},
      ${vars('--shadow-04-key-x')} ${vars('--shadow-04-key-y')} ${vars('--shadow-04-key-blur')} ${vars('--shadow-04-key-spread')} ${vars('--shadow-key')};
  `,
  shadow08: css`
    box-shadow:
      ${vars('--shadow-08-ambient-x')} ${vars('--shadow-08-ambient-y')} ${vars('--shadow-08-ambient-blur')} ${vars('--shadow-08-ambient-spread')} ${vars('--shadow-ambient')},
      ${vars('--shadow-08-key-x')} ${vars('--shadow-08-key-y')} ${vars('--shadow-08-key-blur')} ${vars('--shadow-08-key-spread')} ${vars('--shadow-key')};
  `,
  shadow16: css`
    box-shadow:
      ${vars('--shadow-16-ambient-x')} ${vars('--shadow-16-ambient-y')} ${vars('--shadow-16-ambient-blur')} ${vars('--shadow-16-ambient-spread')} ${vars('--shadow-ambient')},
      ${vars('--shadow-16-key-x')} ${vars('--shadow-16-key-y')} ${vars('--shadow-16-key-blur')} ${vars('--shadow-16-key-spread')} ${vars('--shadow-key')};
  `,
  shadow28: css`
    box-shadow:
      ${vars('--shadow-28-ambient-x')} ${vars('--shadow-28-ambient-y')} ${vars('--shadow-28-ambient-blur')} ${vars('--shadow-28-ambient-spread')} ${vars('--shadow-ambient-darker')},
      ${vars('--shadow-28-key-x')} ${vars('--shadow-28-key-y')} ${vars('--shadow-28-key-blur')} ${vars('--shadow-28-key-spread')} ${vars('--shadow-key-darker')};
  `,
  shadow64: css`
    box-shadow:
      ${vars('--shadow-64-ambient-x')} ${vars('--shadow-64-ambient-y')} ${vars('--shadow-64-ambient-blur')} ${vars('--shadow-64-ambient-spread')} ${vars('--shadow-ambient-darker')},
      ${vars('--shadow-64-key-x')} ${vars('--shadow-64-key-y')} ${vars('--shadow-64-key-blur')} ${vars('--shadow-64-key-spread')} ${vars('--shadow-key-darker')};
  `,
};

export const transitionTime = '0.2s';
